name: Deploy Databricks sandbox to AWS

on:
    pull_request:
        branches:
            - main
        paths:
            - 'environments/**'
    workflow_dispatch:
        inputs:
            env_folder:
                description: 'Environment folder to deploy (e.g., environments/zeerak)'
                required: true
                default: 'environments/zeerak'

jobs:
    deploy:
        runs-on: ubuntu-latest

        env:
            TF_VAR_ADMIN_USER: ${{ secrets.ADMIN_USER }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

        defaults:
            run:
                working-directory: ${{ github.event.inputs.env_folder }}

        steps:
          - name: Checkout repo
            uses: actions/checkout@v3

          - name: Setup Terraform
            uses: hashicorp/setup-terraform@v3
            with:
                terraform_version: 1.6.6

          - name: Terraform Init
            run: terraform init

          - name: Terraform Plan
            run: terraform plan -var-file=terraform.tfvars -out=tfplan

          - name: Terraform Apply (only on PRs to main)
            if: github.event_name == 'pull_request'
            run: terraform apply -auto-approve tfplan
