name: Deploy or Destroy a sandbox for engineer bob

on:
  pull_request:
    branches:
      - main
      - "sandbox/**"
    paths:
      - 'environments/**'

jobs:
  deploy_or_destroy:
    runs-on: ubuntu-latest
    environment: bob

    env:
      TF_VAR_admin_user: ${{ secrets.ADMIN_USER }}
      TF_VAR_client_id: ${{ secrets.CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
      TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      TF_VAR_databricks_account_id: ${{ secrets.DATABRICKS_ACCOUNT_ID }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      TF_VAR_enable_log_delivery: false

    defaults:
      run:
        working-directory: environments/bob

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      # - name: Terraform Plan
      #   run: terraform plan

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve

      - name: Terraform Destroy
        if: contains(join(',', github.event.pull_request.labels.*.name), 'destroy')
        run: terraform destroy -auto-approve
