name: Destroy Databricks Sandbox

on:
  workflow_dispatch:
    inputs:
      env_folder:
        description: 'Environment folder to destroy (e.g., environments/zeerak)'
        required: true
        default: 'environments/zeerak'

jobs:
  destroy:
    runs-on: ubuntu-latest
    #EDIT  HERE:
    environment: bob

    env:
      TF_VAR_admin_user: ${{ secrets.ADMIN_USER }}
      TF_VAR_client_id: ${{ secrets.CLIENT_ID }}
      TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        working-directory: ${{ github.event.inputs.env_folder }}

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Install Databricks CLI and jq
        run: |
          pip install databricks-cli
          sudo apt-get update && sudo apt-get install -y jq

      - name: Run Destroy Script
        run: |
          chmod +x destroy.sh
          ./destroy.sh

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
