name: deploying a sandbox for engineer Bob

on:
    pull_request:
      branches:
        - main
      paths:
        - 'environments/**'
    workflow_dispatch:
      inputs:
        env_folder:
          description: 'Environment folder to deploy  (e.g. environments/zeerak)'
          required: true
          #EDIT HERE:
          default: 'environments/bob'

jobs:
    deploy:
      runs-on: ubuntu-latest
      environment: bob
    #   environment: github.event.inputs.env_folder && fromJson(format('{{"name":"{0}"}}', github.event.inputs.env_folder.split('/')[1])).name || 'bob-test' }}

      env:
        TF_VAR_admin_user: ${{ secrets.ADMIN_USER }}
        TF_VAR_client_id: ${{ secrets.CLIENT_ID }}
        TF_VAR_client_secret: ${{ secrets.CLIENT_SECRET }}
        TF_VAR_aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
        TF_VAR_databricks_account_id: ${{ secrets.DATABRICKS_ACCOUNT_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_enable_log_delivery: false

      defaults:
        run:
            #EDIT HERE:
          working-directory: environments/bob

      steps:
        - name: Checkout repo
          uses: actions/checkout@v3

        - name: Setup Terraform
          uses: hashicorp/setup-terraform@v3
          with:
            terraform_version: 1.6.6

        - name: Terraform Init
          run: terraform init

        - name: Terraform Plan (for pull_request events)
          if: github.event_name == 'pull_request'
          run: terraform plan

        - name: Terraform Apply (manual only)
          if: github.event_name == 'workflow_dispatch'
          run: terraform apply -auto-approve
